$(".green").on("click",function(){
    $(this).hide("slow");
});
$(".red").on("click",function(){
	$(this).hide("slow");
});
$(".blue").on("click",function(){
	$(this).hide("slow");
});
$(".yellow").on("click",function(){
	$(this).hide("slow");
});